-- 03_printer_nodes.sql
CREATE TABLE IF NOT EXISTS printer_nodes (
    node_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country_code CHAR(2) NOT NULL,
    region VARCHAR(100),
    status ENUM('ONLINE', 'OFFLINE', 'MAINTENANCE', 'DECOMMISSIONED') DEFAULT 'ONLINE',
    tier ENUM('SANDBOX', 'CERTIFIED', 'PREMIER') DEFAULT 'SANDBOX',
    reputation_score DECIMAL(5,2) DEFAULT 100.00,
    created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
